# Generated by Django 4.2.13 on 2024-08-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
