# Generated by Django 4.2.13 on 2024-08-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commtent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commtent',
            new_name='Comment',
        ),
    ]
