# Generated by Django 4.2.13 on 2024-08-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_commtent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recip',
            new_name='recipe',
        ),
    ]
